source 'https://rubygems.org'

gem 'berkshelf', '= 7.0.7'
gem 'chefspec', '= 7.3.2'
gem 'foodcritic', '= 14.3.0'
gem 'kitchen-gce'
gem 'kitchen-vagrant'
gem 'rake'
gem 'rubocop'
gem 'stove'
gem 'thor-scmversion'
gem 'test-kitchen'
